// Builds the icon font the app ships. The full Hugeicons font is about 1 MB, so this keeps only the
// icons listed in client/src/ui/icon-names.json: it looks up their code points in the Hugeicons CSS,
// writes client/src/ui/hugeicons.ts and subsets the font to those glyphs with fontTools
// (pip install fonttools brotli). Run it with `npm run icons` after changing the list.
import { execFileSync } from 'node:child_process';
import { readFileSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('..', import.meta.url);
const file = (path) => fileURLToPath(new URL(path, root));

const names = [...new Set(JSON.parse(readFileSync(file('client/src/ui/icon-names.json'), 'utf8')))].sort();
const css = readFileSync(file('client/public/hugeicons/icons.css'), 'utf8');
const codes = new Map();
for (const m of css.matchAll(/\.hgi-([a-z0-9-]+)::before\s*\{\s*content:\s*"\\([0-9a-f]+)"/g)) codes.set(m[1], parseInt(m[2], 16));

const missing = names.filter((n) => !codes.has(n));
if (missing.length) {
  console.error(`Not in client/public/hugeicons/icons.css: ${missing.join(', ')}`);
  process.exit(1);
}

const entries = names.map((n) => `  '${n}': 0x${codes.get(n).toString(16)},`).join('\n');
writeFileSync(
  file('client/src/ui/hugeicons.ts'),
  `// Generated by \`npm run icons\` (scripts/icons.mjs) from icon-names.json. Don't edit by hand.
// Code points of the Hugeicons glyphs in client/public/hugeicons/hgi-subset.woff2.
export const HUGEICONS = {
${entries}
} as const;

export type HugeiconName = keyof typeof HUGEICONS;
`,
);

const out = file('client/public/hugeicons/hgi-subset.woff2');
try {
  execFileSync(
    'pyftsubset',
    [
      file('client/public/hugeicons/hgi-stroke-rounded.woff2'),
      `--unicodes=${names.map((n) => codes.get(n).toString(16)).join(',')}`,
      '--layout-features=',
      '--no-hinting',
      '--flavor=woff2',
      `--output-file=${out}`,
    ],
    { stdio: 'inherit' },
  );
} catch (err) {
  console.error(err.code === 'ENOENT' ? 'pyftsubset not found. Install fontTools: pip install fonttools brotli' : err.message);
  process.exit(1);
}
console.log(`${names.length} icons -> client/public/hugeicons/hgi-subset.woff2 (${(statSync(out).size / 1024).toFixed(1)} KB)`);
